import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Trees",
  description: "A Tree Link",
};

export default function tree () {
  return (
    <section>
      <p></p>trees are better than bushes. 
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.
      Trees are better.


    </section>
  );
}